// <auto-generated />
using DontEatAlone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DontEatAlone.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DontEatAlone.Data.Comment", b =>
                {
                    b.Property<int>("id");

                    b.Property<string>("authorID");

                    b.Property<string>("body");

                    b.Property<DateTime>("date");

                    b.Property<int>("reservationID");

                    b.HasKey("id");

                    b.HasIndex("reservationID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("DontEatAlone.Data.Limitations", b =>
                {
                    b.Property<int>("id");

                    b.Property<string>("age");

                    b.Property<bool>("alcohol");

                    b.Property<string>("cuisineType");

                    b.Property<string>("description");

                    b.Property<string>("gender");

                    b.Property<string>("languages");

                    b.Property<bool>("pets");

                    b.Property<bool>("smoking");

                    b.HasKey("id");

                    b.ToTable("Limitations");
                });

            modelBuilder.Entity("DontEatAlone.Data.PremiumSubscription", b =>
                {
                    b.Property<string>("ID");

                    b.Property<DateTime>("endDate");

                    b.Property<bool>("payment");

                    b.Property<DateTime>("startDate");

                    b.HasKey("ID");

                    b.ToTable("PremiumSubscription");
                });

            modelBuilder.Entity("DontEatAlone.Data.Reservation", b =>
                {
                    b.Property<int>("id");

                    b.Property<string>("LocationID");

                    b.Property<DateTime>("dateEnd");

                    b.Property<DateTime>("dateStart");

                    b.Property<int>("numberOfPeople");

                    b.Property<string>("status");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("DontEatAlone.Data.User", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("dateOfBirth");

                    b.Property<string>("email");

                    b.Property<string>("firstName");

                    b.Property<string>("gender");

                    b.Property<string>("lastName");

                    b.Property<string>("phoneNumber");

                    b.Property<string>("userType");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DontEatAlone.Data.UserReservation", b =>
                {
                    b.Property<string>("userID");

                    b.Property<int>("reservationID");

                    b.Property<bool>("isHost");

                    b.HasKey("userID", "reservationID");

                    b.HasAlternateKey("reservationID", "userID");

                    b.ToTable("UserReservation");
                });

            modelBuilder.Entity("DontEatAlone.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DontEatAlone.Data.Comment", b =>
                {
                    b.HasOne("DontEatAlone.Data.Reservation", "Reservation")
                        .WithMany("Comments")
                        .HasForeignKey("reservationID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DontEatAlone.Data.Limitations", b =>
                {
                    b.HasOne("DontEatAlone.Data.Reservation", "Reservation")
                        .WithOne("Limitations")
                        .HasForeignKey("DontEatAlone.Data.Limitations", "id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DontEatAlone.Data.PremiumSubscription", b =>
                {
                    b.HasOne("DontEatAlone.Data.User", "User")
                        .WithOne("PremiumSubscription")
                        .HasForeignKey("DontEatAlone.Data.PremiumSubscription", "ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DontEatAlone.Data.User", b =>
                {
                    b.HasOne("DontEatAlone.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("User")
                        .HasForeignKey("DontEatAlone.Data.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DontEatAlone.Data.UserReservation", b =>
                {
                    b.HasOne("DontEatAlone.Data.Reservation", "Reservation")
                        .WithMany("UserReservations")
                        .HasForeignKey("reservationID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DontEatAlone.Data.User", "User")
                        .WithMany("UserReservations")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DontEatAlone.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DontEatAlone.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DontEatAlone.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DontEatAlone.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
